name: Validate and Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  build-branch:
    name: Build, branch, publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup and run tests
        uses: ./.github/actions/setup-and-run-tests

      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          scheme: calver

      - name: Set version
        shell: bash
        run: |
          set -e -x -o pipefail
          poetry version ${{ steps.version.outputs.version }}

      - name: Create release branch
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actor
          new_branch: release/${{ steps.version.outputs.version }}
          push: true

      - name: Build release
        shell: bash
        run: |
          set -e -x -o pipefail
          poetry build

      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          repository-url: https://test.pypi.org/legacy/
      
      - name: Upload release as artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/*.whl
